### ISSUE TITLE
Progress Dialog crashes from a fragment

### ISSUE THREAD

**Issue by martipello** [BROUDING/SimpleDialog#4]
java.lang.NoSuchMethodError: No virtual method into(Landroid/widget/ImageView;)Lcom/bumptech/glide/request/target/Target; in class Lcom/bumptech/glide/RequestBuilder; or its super classes (declaration of 'com.bumptech.glide.RequestBuilder' appears in /data/app/com.sealstudios.aimessage-LPny1SL3Eq0TjC_Cef3cHg==/split_lib_dependencies_apk.apk)
                                                                             at com.brouding.simpledialog.SimpleDialog.setProgressBar(SimpleDialog.java:159)
                                                                             at com.brouding.simpledialog.SimpleDialog.setLayout(SimpleDialog.java:212)
                                                                             at com.brouding.simpledialog.SimpleDialog.<init>(SimpleDialog.java:365)
                                                                             at com.brouding.simpledialog.SimpleDialog$Builder.build(SimpleDialog.java:702)
                                                                             at com.brouding.simpledialog.SimpleDialog$Builder.showDialog(SimpleDialog.java:726)
                                                                             at com.brouding.simpledialog.SimpleDialog$Builder.show(SimpleDialog.java:711)

I'm also using glide in my project i dont know if this is related or not, it doesnt appear to be

**Comment by BROUDING** [comment]
@martipello I'm sorry for late reply, which version of Glide are you using?

**Comment by martipello** [comment]
I was using version 4

**Comment by BROUDING** [comment]
@martipello I've been using 4.0.0 version and the most recent version is 4.7.1
Are you using 4.7.1 version?

**Comment by martipello** [comment]
Yeah I'm using 4.7.1 sorry glide calls them V3 and v4

**Comment by BROUDING** [comment]
@martipello I just tested with V.4.7.1 and I had the same issue and I could only assume it's something to do with Glide's version changing..

I'll upgrade SimpleDialog's Glide version later (For personal reason),
For now, if you still want to use SimpleDialog, I know it's lame, but you can change your project's Glide version to V.4.3.1 and it will work.

I'm sorry for now this is all I can do :/

**Comment by martipello** [comment]
That's awesome I've got no issue with rolling glide back to 4.3.1 if that's
all it'll take shouldn't be any breaking changes thanks very much

**Comment by BROUDING** [comment]
Well, I am sorry that's all I can do for now.

Have a nice day !
